// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGR9EfyfcRGCMmTsT774UdcPp7ZkvX86M',
    appId: '1:1023001830479:web:114b92014aafb1be0db63a',
    messagingSenderId: '1023001830479',
    projectId: 'expense-tracker-648c8',
    authDomain: 'expense-tracker-648c8.firebaseapp.com',
    storageBucket: 'expense-tracker-648c8.appspot.com',
    measurementId: 'G-VX6CJD8YC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3DSB6WcGWsTSP08kscM6FmLtqWqJuuOs',
    appId: '1:1023001830479:android:407eddf3879cfef60db63a',
    messagingSenderId: '1023001830479',
    projectId: 'expense-tracker-648c8',
    storageBucket: 'expense-tracker-648c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHuLnXPf3RuFyKPkf2VhColtnArofCXJk',
    appId: '1:1023001830479:ios:ef4de9884c31ab0f0db63a',
    messagingSenderId: '1023001830479',
    projectId: 'expense-tracker-648c8',
    storageBucket: 'expense-tracker-648c8.appspot.com',
    iosBundleId: 'com.example.expense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHuLnXPf3RuFyKPkf2VhColtnArofCXJk',
    appId: '1:1023001830479:ios:2bf5b16a6ea6f4cb0db63a',
    messagingSenderId: '1023001830479',
    projectId: 'expense-tracker-648c8',
    storageBucket: 'expense-tracker-648c8.appspot.com',
    iosBundleId: 'com.example.expense.RunnerTests',
  );
}
